# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x1d1f23ff
rootcolor = 0x21252bff
bordercolor = 0x666e7eff
focuscolor = 0x62bac6ff
maximizescreencolor = 0xeac786ff
urgentcolor = 0xe27881ff
scratchpadcolor = 0x98c379ff
globalcolor = 0x16565fff
overlaycolor = 0xb0770eff
