#!/bin/sh

DIALOG_RESULT=$(echo -e 'Quit Spectrwm\nReboot\nPoweroff' | dmenu -i -nb '#282a36' -nf '#c3cdc8' -sb '#6272a4' -fn 'JetBrains Mono Nerd Font-12' -p "SYSTEM" )

case $DIALOG_RESULT in
        "Quit Spectrwm" ) pkill spectrwm ;;
        "Reboot") systemctl reboot ;;
        "Poweroff") systemctl poweroff ;;
        *) exit 0
esac
