#!/bin/sh

DIALOG_RESULT=$(echo -e 'Quit i3\nHibernate\nReboot\nPoweroff' | dmenu -i -nb '#282a36' -nf '#c3cdc8' -sb '#6272a4' -fn 'JetBrains Mono Nerd Font-12' -p "SYSTEM" )

case $DIALOG_RESULT in
        "Quit i3" ) fancy-quit ;;
        "Hibernate") systemctl hibernate ;;
        "Reboot") systemctl reboot ;;
        "Poweroff") systemctl poweroff ;;
        *) exit 0
esac
