#!/usr/bin/env bash

DIALOG_RESULT=$(echo -e 'Quit\nReboot\nPoweroff' | dmenu -p 'System')

case $DIALOG_RESULT in
        "Quit") fancy-quit && dkcmd exit ;;
        "Reboot") fancy-quit && systemctl reboot ;;
        "Poweroff") fancy-quit && systemctl poweroff ;;
        *) exit 0
esac
