#!/usr/bin/env sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"


# LAUNCHERS
killall cleanfullscreen
cleanfullscreen &
 pkill sxhkd
 pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &

# ----------------------------------------------------------------------------------------------


# Bspwm configs
bspc config border_width         5
bspc config window_gap           10
bspc config top_padding          35
bspc config bottom_padding       10
bspc config right_padding        10
bspc config left_padding         10
bspc config split_ratio          0.50


bspc config borderless_monocle    false  # no borders in monocle layout.
bspc config gapless_monocle       false  # no gaps in monocle layout.
bspc config single_monocle        true  # use monocle layout if there is only 1 window.
bspc config automatic_scheme alternate
bspc config center_pseudo_tiled   true
#bspc config initial_polarity second_child
bspc config focus_follows_pointer true
bspc config honor_size_hints 	 true
#bspc config external_rules_command $HOME/.config/bspwm/spotify_rules
#b#spc config external_rules_command $HOME/.local/bin/float.sh
#bspc config external_rules_command $HOME/.config/bspwm/external_rules.sh
#bspc config remove_disabled_monitors true
#bspc config merge_overlapping_monitors true


# Moving foating windows
bspc config pointer_motion_interval   5
bspc config pointer_modifier          mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner


# Border colors
bspc config normal_border_color $(awk '$1 ~ "background" { print $2 }' ~/.Xresources)
bspc config active_border_color $(awk '$1 ~ "color4" { print $2 }' ~/.Xresources)
bspc config focused_border_color $(awk '$1 ~ "color4" { print $2 }' ~/.Xresources)
#bspc config presel_feedback_color $(awk '$1 ~ "red" { print $2 }' ~/.Xresources)
#bspc config urgent_border_color $(awk '$1 ~ "$color8" { print $2 }' ~/.Xresources)


# Single monitor choice
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor  -d "☢️ " "🤬 " "⚒️ " "🍭 " "🎲 " "🎬 " "🔰 "  "🎯 " "📀 "
#bspc monitor -d "Web " "Chat " "Edit " "Music " "Tor " "Video " "Vbox " "File " "Float "
bspc monitor -d ""  ""  ""  ""  ""  ""  ""  ""  ""  ""
#bspc monitor -d "I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X"


# Dual monitor example
# bspc monitor DP-0 -d 1 3 4 5 6 7 8
# bspc monitor HDMI-0 -d 2
# bspc monitor DP-0 -s HDMI-0





# Open applications on specific workspaces
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a discord desktop='^2' follow=on
bspc rule -a eadesktop.exe desktop='^6' state=pseudo_tiled follow=on
bspc rule -a Sublime_text desktop='^3' follow=on
bspc rule -a steam desktop='^4' state=pseudo_tiled follow=on
bspc rule -a Vlc desktop='^7' state=fullscreen follow=on
bspc rule -a qBittorrent desktop='^7' follow=on
bspc rule -a Thunar desktop='^8' follow=on
bspc rule -a Pcmanfm desktop='^8' follow=on
bspc rule -a Spotify desktop='^9' follow=on
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
#bspc rule -a Ulauncher  border=off
bspc rule -a Lutris desktop='^5' follow=on
#bspc rule -a scpad sticky=on state=floating rectangle=1880x1000+940+500
#bspc rule -a ncmpcpp sticky=on state=floating rectangle=1880x1000+940+500

# Floating apps
bspc rule -a heroic.exe desktop='^6' state=pseudo_tiled follow=on
bspc rule -a Lxappearance state=floating rectangle=1480x800+540+300
bspc rule -a Xfce4-appfinder state=floating rectangle=1480x800+540+300
bspc rule -a Pavucontrol state=floating rectangle=1480x800+540+300
bspc rule -a Pcmanfm:Dialog state=floating
bspc rule -a Alacritty:Alacritty:News state=floating rectangle=1480x800+540+300
bspc rule -a Alacritty:Alacritty:Music state=floating rectangle=1480x800+540+300
bspc rule -a com.github.neithern.g4music state=floating rectangle=1480x800+540+300 border=off
bspc rule -a Alacritty:Alacritty:scratchpad state=floating rectangle=1480x800+540+300
bspc rule -a upc.exe desktop='^6' state=pseudo_tiled private=on follow=on
bspc rule -a Sxiv state=floating rectangle=1480x800+540+300
bspc rule -a mpv state=floating rectangle=800x400+1730+50
bspc rule -a epicgameslauncher.exe desktop='^6' state=pseudo_tiled follow=on
# Manage apps
bspc rule -a polybar manage=off
bspc rule -a Screenkey manage=off
#bspc rule -a xfce4-panel manage=off

###########END####################################################################
